[tox]
envlist =
    py39-dj32,
    py39-dj42,
    py39-dj50,
    py39-dj51,
    py310-dj32,
    py310-dj42,
    py310-dj50,
    py310-dj51,
    py311-dj32,
    py311-dj42,
    py311-dj50,
    py311-dj51,
    py312-dj32,
    py312-dj42,
    py312-dj50,
    py312-dj51

[testenv]
basepython =
    py39: python3.9
    py310: python3.10
    py311: python3.11
    py312: python3.12

deps =
    pytz
    python-dateutil
    dj32: Django>=3.2,<3.3
    dj42: Django>=4.2,<4.3
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2

commands =
    ./runtests.py
