# Generated by Django 6.0 on 2025-12-18 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('rrule', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('exdates_json', models.JSONField(blank=True, default=list)),
                ('rdates_json', models.JSONField(blank=True, default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='eventtools.baseevent')),
            ],
        ),
        migrations.CreateModel(
            name='MyEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventtools.baseevent')),
            ],
            bases=('eventtools.baseevent',),
        ),
        migrations.CreateModel(
            name='MyOccurrence',
            fields=[
                ('baseoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventtools.baseoccurrence')),
            ],
            bases=('eventtools.baseoccurrence',),
        ),
        migrations.CreateModel(
            name='MyOtherOccurrence',
            fields=[
                ('baseoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventtools.baseoccurrence')),
            ],
            bases=('eventtools.baseoccurrence',),
        ),
    ]
