# Generated by Django 6.0 on 2025-12-20 07:06

import django.db.models.deletion
import eventtools.occurrence
import eventtools.query
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.query.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='BaseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('rrule', models.TextField(blank=True, null=True)),
                ('exdates_json', models.JSONField(blank=True, default=list)),
                ('rdates_json', models.JSONField(blank=True, default=list)),
                ('repeat_until', models.DateField(blank=True, null=True, verbose_name='repeat_until')),
                ('repeat', eventtools.occurrence.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='', verbose_name='repeat')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='eventtools.baseevent')),
            ],
        ),
    ]
