# Generated by Django 6.0 on 2025-12-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOtherOccurrence',
            fields=[
                ('baseoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventtools.baseoccurrence')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventtools.myevent')),
            ],
            bases=('eventtools.baseoccurrence',),
        ),
    ]
